weibocom/breeze

stream/src/chan/get_by_layer.rs
只有开启debug log时，才准备response的data并打印。
=> only copy response data and log when debug

endpoint/src/cacheservice/topo.rs, sharding/src/hash/bkdr.rs, sharding/src/hash/crc32.rs, sharding/src/hash/mod.rs, sharding/src/hash/raw.rs, sharding/src/lib.rs, tests/src/shard_test.rs
1. 支持#作为分隔符进行key hash；
2. 重构hash，支持3类key，同时对crc32-delimiter模式，可以一行代码扩展新的分隔符。
=> 支持‘#’做分隔符的key，重构hash，支持单行扩展新分隔符

endpoint/src/phantomservice/topo.rs, protocol/src/phantom/command.rs, protocol/src/phantom/mod.rs, stream/src/handler.rs
1 对所有负数rsp均重试，包括疑似非法key-2（因为非法key跟实例判断有关，如果不重试，在后续phantom升级可能会遇到问题）；   
2 调整bfmset的返回格式。
=> 修改phantom协议处理

protocol/src/redis/command.rs
打开zrevrank、zrevrangebyscore两个指令，并修改commands的hash算法为bkdr。
=> Support new cmds

agent/src/http.rs, agent/src/main.rs, agent/src/service.rs, context/Cargo.toml, context/src/lib.rs, discovery/src/lib.rs, discovery/src/socks.rs, protocol/src/error.rs, protocol/src/memcache/binary/mod.rs, protocol/src/parser.rs, protocol/src/phantom/command.rs, protocol/src/phantom/mod.rs, protocol/src/redis/command.rs, protocol/src/redis/mod.rs, stream/src/metric.rs, stream/src/pipeline.rs
1. multi 指令过滤异常信息，发送对应的nil值，并对nilconvert进行统计；（$-1, :-10）  
2. 支持从vintage都去socks列表，并构建socks文件；
3. 对unsupport cmd，进行日志及统计，修复之前的统计异常；  
4. 对init失败、监听、accept失败，都增加ns监听失败的计数。
=> 1 filter err for multi cmds; 2 support reading socks from vintage

.gitignore, metrics/src/packet.rs, metrics/src/register.rs, metrics/src/sender.rs, rt/src/entry.rs, rt/src/stream/mod.rs, stream/src/handler.rs, stream/src/pipeline.rs
将所有依赖的 ds::ready 替换成rust 1.64中的std::task::ready
=> replace ds::ready to 1.64 std::task::ready which

endpoint/src/redisservice/config.rs, sharding/src/distribution/mod.rs
随着dist大量引入，很多dist不需要对后端数量进行限制，调整限制逻辑，当前只对range、modrange及其这两种衍生类型才进行2^n限制。
=> 只对range/modrange类dist进行后端数量限制

protocol/src/redis/command.rs, protocol/src/redis/mod.rs, protocol/src/redis/packet.rs
当前redis cmd新模式增加了master_next属性，故将master指令改用标准解析流程，更方便快捷。
=> 修改redis的master指令到标准解析流程

ds/src/mem/ring_slice.rs, protocol/src/error.rs, protocol/src/msgque/mcq/text/rsppacket.rs, protocol/src/redis/command.rs, rt/src/entry.rs, stream/src/buffer.rs, stream/src/checker.rs, stream/src/reconn.rs
1 请求遇到网络异常不再等待，立即返回异常；
2 geo两个指令：georadiusCommand、georadiusbymemberCommand，从get调整为store类型；
3 调整hello参数个数（为啥返回Err？）
4 调整重连策略，避免超时等异常后failfast。
=> 修复请求异常及geo指令路由问题

stream/src/reconn.rs
连接失败时，也修改ReconnPolicy的conn计数，这样方便日志记录查看
=> 连接失败时，也修改ReconnPolicy的conn计数

agent/src/main.rs, context/src/lib.rs, stream/src/pipeline.rs
socklist的部分代码在merge中丢失，恢复支持。  
策略说明：如果按服务池在vintage设置socklist，则以vintage为准。即：本地多余的sock会被清理，缺少的socks会被补上。
=> 恢复功能：socklist从vintage获取

ds/src/mem/guarded.rs, ds/src/mem/ring_slice.rs, protocol/src/callback.rs, protocol/src/memcache/binary/mod.rs, protocol/src/memcache/binary/packet.rs, protocol/src/msgque/mcq/text/command.rs, protocol/src/msgque/mcq/text/mod.rs, protocol/src/parser.rs, protocol/src/phantom/command.rs, protocol/src/phantom/flag.rs, protocol/src/phantom/mod.rs, protocol/src/redis/command.rs, protocol/src/redis/flag.rs, protocol/src/redis/mod.rs, stream/src/context.rs, stream/src/metric.rs, stream/src/pipeline.rs, tests/src/redis.rs
1 将response的构建统一放在write_rsp的时候（整合write_noforward、build_local 到 write_rsp）；   
2 整合padding和nil rsp;   
3 req、resp、dist_fn整合到respContext中；  
4 flag去掉padding_rsp;  
5 pipeline中的协议相关metrics调整到protocol；
=> 修改response的处理逻辑

stream/src/pipeline.rs
CopyDirectional在close时，如果request中已经记入response，需要take走，确保drop的状态一致性，避免assert失败。
=> pipeline的close中需要take resp

endpoint/src/phantomservice/topo.rs, endpoint/src/redisservice/topo.rs
修改应对两种可能的变更状态丢失：  
1. 本次更新失败后，不能丢失本次的变更通知，需要下次重试；  
2. 本次更新过程中，如果正好有状态更新通知，不能丢失新的更新通知；
=> 避免topo更新失败后丢失本次待变更通知

sharding/src/hash/crc32.rs, sharding/src/hash/crc32local.rs, sharding/src/hash/mod.rs
支持新hash： crc32-smartnum  和 crc32local-smartnum  。  
对格式如： xxx + $id + xxx，以第一个连续长度大于等于5的数字，作为key的hashkey。算法支持crc32 和 crc32local。
=> support new hash: crc32-smartnum & crc32local-smartnum

protocol/src/memcache/binary/mod.rs, protocol/src/memcache/binary/packet.rs, protocol/src/msgque/mcq/binary/mod.rs
gets 在资源异常时，没有处理，从而默认返回Err，导致mesh和sdk之间的连接断开；   
修改为：返回empty response。
=> 后端资源异常时，对gets需要返回空响应，避免异常断连

sharding/src/hash/crc32.rs, sharding/src/hash/mod.rs
支持crc32-mixnum： key中前两个字串id拼接为一个id，作为hashkey。     
eg： 123_456_w、abc_123_456_def、123#456.def 的hashkey都是：123456
=> support new hash: crc32-mixnum

sharding/src/hash/crc32.rs, sharding/src/hash/mod.rs
支持crc32-mixnum： key中前两个字串id拼接为一个id，作为hashkey。    
eg： 123_456_w、abc_123_456_def、123#456.def 的hashkey都是：123456
=> Support hash mixnum

endpoint/src/cacheservice/config.rs, endpoint/src/cacheservice/topo.rs, endpoint/src/redisservice/config.rs, endpoint/src/redisservice/topo.rs
若环境变量 BREEZE_LOCAL 的取值为允许local，则访问资源时按local的策略访问资源；否则按照资源元数据配置决定是否按local的策略访问该资源
=> 优先从环境变量获取资源访问local策略

context/src/lib.rs, discovery/src/distance.rs, sharding/Cargo.toml, sharding/src/select/by_distance.rs
1. breeze启动参数支持指定可用区，如果指定，取值限定为[cn1, cn2, cn3]
2. breeze启动时指定有效可用区，且redis资源配置启用可用区才生效
=> 启动参数支持指定可用区

protocol/src/error.rs, protocol/src/kv/mc2mysql.rs
前一版本，为避免merge时的大量代码冲突（dev有代码搬迁），暂时保留Error::MysqlError；
目前已merge完毕，可以清理了。
=> 清理前一版本临时保留MysqlError

protocol/src/kv/common/query_result.rs, protocol/src/kv/mod.rs, protocol/src/kv/rsppacket.rs
使用代理方法统一构建待返回的rsp/err cmd，强制在返回响应前进行数据流的take。
=> 重构kv的响应解析方法

discovery/Cargo.toml, discovery/src/distance.rs, endpoint/Cargo.toml, endpoint/src/redisservice/config.rs, endpoint/src/redisservice/topo.rs, metrics/src/lib.rs, metrics/src/macros.rs, metrics/src/types/host.rs, metrics/src/types/mod.rs, metrics/src/types/number.rs, sharding/src/select/by_distance.rs
与#383的区别是：#383采用全局变量+lock，只推0；本方案是开启可用区，则可用区内的资源数量都推，按资源/端口维度推监控
=> 可用区内资源数量监控

protocol/src/memcache/binary/mod.rs, tests_integration/src/redis/basic/shard.rs
deleteq 可能会返回异常，此时不需要断连接，直接忽略即可；     
deleteq 在kv不存在时，返回的异常： not-found
=> mc deleteq收到异常响应，不再断连接，改为忽略异常响应

endpoint/src/redisservice/config.rs
redis资源如果selector字段没有配置，默认值为`timeslice`
=> redis后端资源配置里的selector默认为timeslice

protocol/src/kv/common/bitflags_ext.rs, protocol/src/kv/common/io.rs, protocol/src/kv/common/query_result.rs, protocol/src/kv/mod.rs, protocol/src/memcache/binary/packet.rs
Rust官方正式发布 1.78.0之后，github CI编译报错。本次修改仅为了消除这些编译报错。
=> 消除rust 1.78.0编译warn

protocol/src/redis/command.rs
python3 redis客户端初始化时，依赖hello和client指令。为方便在mac下的测试，做如下适配：
1. 简化支持hello指令，示例如下：
```
> HELLO
1) "proto"
2) (integer) 2
```
2. debug模式下简单支持client指令，直接返回+OK
=> 简化支持hello指令、debug模式下简单支持client指令

discovery/src/update.rs
对于mc，group是all，不同业务可能存在冲突覆盖，导致端口无法监听，改为full group存储。
=> 解决discovery时group冲突问题

protocol/src/kv/common/error/mod.rs, protocol/src/vector/query_result.rs, stream/src/checker.rs
线上同一个服务池不同实例间unexpected_resp监控数量不一致，需要输出log进一步分析；后续再将本commit revert掉。
=> 打印backend退出原因

protocol/src/redis/mod.rs
第84行解析响应消息类型为字符串，当返回成功时，字符串内容不一定完成接收
=> redis响应类型为字符串时，如果未完整接收，返回ProtocolIncomplete

endpoint/src/msgque/strategy/round_robbin.rs, protocol/src/msgque/mod.rs, tests_integration/src/mq/mod.rs
=> 在写改为轮询写后，读去掉盯读，且在miss后不重试

endpoint/src/lib.rs
特殊业务需要较小的超时时间，目前配置里的超时时间也是20ms
=> 后端资源超时时间允许最小20ms

protocol/src/kv/mod.rs, protocol/src/memcache/binary/mod.rs, protocol/src/parser.rs, sharding/src/hash/mod.rs, stream/src/handler.rs, stream/src/pipeline.rs
kv 在sdk交互时走mc binary协议，get miss 这种get类型的error不统计，只统计store类型的error
=> kv 不统计err req
