weibocom/breeze

- endpoint/src/cacheservice/mod.rs
- stream/src/chan/sharding.rs
修复get sharding 请求的bug，需要按key进行hash并分布。
> fix bug in get: hash with key

- protocol/src/lib.rs
- protocol/src/memcache/binary/meta.rs
- protocol/src/memcache/binary/mod.rs
- protocol/src/memcache/binary/packet.rs
- protocol/src/request.rs
- stream/src/chan/get_by_layer.rs
- stream/src/chan/multi_get_sharding.rs
> Support write back

- protocol/src/memcache/binary/mod.rs
- stream/src/chan/multi_get_sharding.rs
> update write back log

- endpoint/src/cacheservice/mod.rs
- stream/src/chan/get_by_layer.rs
- stream/src/chan/multi_get_sharding.rs
layer 获取，去掉multi_get_sharding的noreply逻辑，回写统一采用AsyncSharding
> remove noreply in getssharding

- agent/src/main.rs
> Revert "Mc 4 thread"

- endpoint/src/redisservice/topo.rs
- protocol/src/redis/command.rs
- sharding/src/distribution/mod.rs
- sharding/src/distribution/modrange.rs
- sharding/src/distribution/range.rs
- sharding/src/distribution/splitmod.rs
- sharding/src/hash/mod.rs
- sharding/src/hash/raw.rs
- tests/src/distribute.rs
- tests/src/hash_test.rs
- tests/src/lib.rs
1. 增加支持raw hash； 
2. range增加slot特性，支持各种slot槽数（即client的hash gen）。
3. 增加新的distribution：modrange、splitmod
> support more hash & distribute strategies

- protocol/src/redis/command.rs
> update ltrim cmd prop

- endpoint/src/cacheservice/config.rs
- endpoint/src/cacheservice/topo.rs
- endpoint/src/redisservice/topo.rs
- tests/src/lib.rs
- tests/src/redis.rs
支持业务sdk参数force_write_all，对force_write_all、exptime测试环境通过。
> support mc sdk config

- endpoint/src/cacheservice/config.rs
- endpoint/src/cacheservice/topo.rs
- sharding/src/hash/crc32.rs
- sharding/src/hash/mod.rs
- sharding/src/lib.rs
- tests/src/redis.rs
1 crc32 转 crc32-short改到cfg parse中；   
2 调整部分日志级别；
3 其他格式类及test的小调整。
> crc32 转 crc32-short改到cfg parse中；调整部分日志级别

- endpoint/src/redisservice/topo.rs
- sharding/src/hash/bkdr.rs
- sharding/src/hash/crc32.rs
- tests/src/hash_test.rs
- tests/src/lib.rs
- tests/src/ring_slice.rs
- tests/src/shard_test.rs
> Dev add log

- sharding/src/distribution/mod.rs
- sharding/src/distribution/slotmod.rs
- tests/src/distribute.rs
支持slotmod distribution，算法： hash() % slot % mod
> support new distribution: slotmod

- discovery/src/dns.rs
- endpoint/src/cacheservice/config.rs
- endpoint/src/cacheservice/topo.rs
- protocol/src/flag.rs
- protocol/src/memcache/binary/mod.rs
- protocol/src/memcache/binary/packet.rs
1 支持update_slave_l1;       
2 fix bug for dns checking：原逻辑对扩ip，无法感知;     
3 try next对不同指令设置不同的逻辑：如果cas/add 直接是false，del必须是true，普通set跟force write all相关。
> 1 支持update_slave_l1; 2 fix bug for dns checking

- endpoint/src/cacheservice/config.rs
> mc 支持不设置配置:update_slave_l1

- endpoint/src/redisservice/topo.rs
- protocol/src/redis/mod.rs
- stream/src/buffer.rs
> Update buff size

- endpoint/src/redisservice/config.rs
- endpoint/src/redisservice/topo.rs
- protocol/src/redis/command.rs
- sharding/src/distribution/mod.rs
- sharding/src/distribution/modula.rs
> support cmd: strlen

- sharding/src/hash/crc32local.rs
- sharding/src/hash/mod.rs
- sharding/src/hash/rawcrc32local.rs
- tests/src/lib.rs
- tests/src/shard_test.rs
> Support crc32local

- ds/src/mem/ring_slice.rs
- endpoint/src/phantomservice/topo.rs
- endpoint/src/redisservice/topo.rs
- protocol/src/flag.rs
- protocol/src/parser.rs
- protocol/src/phantom/flag.rs
- protocol/src/redis/command.rs
- protocol/src/redis/flag.rs
- protocol/src/redis/mod.rs
- protocol/src/redis/packet.rs
- protocol/src/req.rs
- protocol/src/request.rs
支持xxxFromMaster指令，方式在指令之前发出一个标准的master指令。
> Support master only

- agent/src/service.rs
- endpoint/src/redisservice/topo.rs
- protocol/Cargo.toml
- protocol/src/callback.rs
- protocol/src/error.rs
- protocol/src/flag.rs
- protocol/src/memcache/binary/error.rs
- protocol/src/memcache/binary/mod.rs
- protocol/src/memcache/binary/packet.rs
- protocol/src/parser.rs
- protocol/src/phantom/error.rs
- protocol/src/phantom/flag.rs
- protocol/src/phantom/mod.rs
- protocol/src/phantom/packet.rs
- protocol/src/redis/command.rs
- protocol/src/redis/error.rs
- protocol/src/redis/flag.rs
- protocol/src/redis/mod.rs
- protocol/src/redis/packet.rs
- protocol/src/req.rs
- protocol/src/request.rs
- sharding/src/distribution/modrange.rs
- sharding/src/distribution/range.rs
- stream/src/buffer.rs
- stream/src/handler.rs
- stream/src/metric.rs
- stream/src/pipeline.rs
支持新的吞噬指令： hashkey   
支持lua相关指令。
> Support lua

- agent/src/main.rs
- agent/src/service.rs
- context/src/lib.rs
- metrics/src/types/host.rs
- metrics/src/types/mod.rs
> sockfile 解析失败or冲突时，打日志并汇报

- endpoint/src/lib.rs
- endpoint/src/msgque/config.rs
- endpoint/src/msgque/mod.rs
- endpoint/src/msgque/topo.rs
- endpoint/src/topo.rs
- protocol/src/lib.rs
- protocol/src/msgque/mcq/binary/error.rs
- protocol/src/msgque/mcq/binary/mod.rs
- protocol/src/msgque/mcq/binary/packet.rs
- protocol/src/msgque/mcq/mod.rs
- protocol/src/msgque/mcq/text/command.rs
- protocol/src/msgque/mcq/text/error.rs
- protocol/src/msgque/mcq/text/mcreqpacket.rs
- protocol/src/msgque/mcq/text/mcrsppacket.rs
- protocol/src/msgque/mcq/text/mod.rs
- protocol/src/msgque/mcq/text/reqpacket.rs
- protocol/src/msgque/mcq/text/rsppacket.rs
- protocol/src/msgque/mod.rs
- protocol/src/parser.rs
- sharding/src/distribution/mod.rs
- sharding/src/distribution/padding.rs
- sharding/src/hash/mod.rs
- sharding/src/hash/padding.rs
> support msgqueue

- endpoint/src/msgque/topo.rs
- protocol/src/lib.rs
mq写消息策略调整：确认写入size的queue列表后，随机选择写入节点。
> mq write with rand strategy

- protocol/src/msgque/mcq/text/reqpacket.rs
> Update mcq parse

- context/src/lib.rs
- metrics/src/types/host.rs
changes:
1. add startup arg `--cpu`, default value is `vx`
2. append `--cpu` value to `version`
> add startup arg --cpu

- endpoint/src/msgque/mod.rs
- endpoint/src/msgque/topo.rs
- endpoint/src/phantomservice/topo.rs
- endpoint/src/redisservice/topo.rs
- protocol/src/callback.rs
- protocol/src/memcache/binary/mod.rs
- protocol/src/msgque/mcq/binary/mod.rs
- protocol/src/msgque/mcq/text/command.rs
- protocol/src/msgque/mcq/text/mcreqpacket.rs
- protocol/src/msgque/mcq/text/mcrsppacket.rs
- protocol/src/msgque/mcq/text/mod.rs
- protocol/src/msgque/mcq/text/reqpacket.rs
- protocol/src/msgque/mcq/text/rsppacket.rs
- protocol/src/operation.rs
- protocol/src/phantom/command.rs
- protocol/src/phantom/mod.rs
- protocol/src/phantom/packet.rs
- protocol/src/redis/command.rs
- protocol/src/redis/mod.rs
- protocol/src/redis/packet.rs
- rt/src/stream/mod.rs
> assert 增加上下文日志&mcq parse修改

- protocol/src/error.rs
- rt/src/entry.rs
> 发现异常立即断连返回

- discovery/src/dns.rs
> dns refresh

- stream/src/pipeline.rs
> Update pipeline start init

- metrics/src/types/rtt.rs
- protocol/src/memcache/binary/mod.rs
- protocol/src/msgque/mcq/text/mod.rs
- protocol/src/parser.rs
- protocol/src/phantom/mod.rs
- protocol/src/redis/mod.rs
- stream/src/context.rs
- stream/src/metric.rs
- stream/src/pipeline.rs
> Dev pro metric

- .github/workflows/rust.yml
- protocol/src/redis/mod.rs
- protocol/src/redis/packet.rs
解析redis request及response时，根据协议进行reserve stream buff
> 解析redis的请求&响应时及时进行空间reserve

- protocol/src/msgque/mcq/text/mod.rs
- stream/src/metric.rs
- stream/src/pipeline.rs
- tests/src/layout.rs
> Revert "mcq err metric"

- discovery/src/dns.rs
- endpoint/src/phantomservice/config.rs
- endpoint/src/phantomservice/mod.rs
- endpoint/src/phantomservice/topo.rs
- endpoint/src/redisservice/topo.rs
- endpoint/src/shards.rs
- protocol/src/phantom/mod.rs
- sharding/src/hash/bkdr.rs
- tests/Cargo.toml
- tests/src/benches/criterion.rs
- tests_integration/src/phantom.rs
- tests_integration/src/redis/basic/limit.rs
1 写：根据配置，默认写所有分组；
2 读：先读本地，失败重试其他；
todo：load时，需要排序
> phantom写根据配置进行local单写 or 全分组写

- .github/workflows/rust.yml
- endpoint/src/lib.rs
- endpoint/src/phantomservice/config.rs
- endpoint/src/phantomservice/mod.rs
- endpoint/src/phantomservice/topo.rs
- endpoint/src/redisservice/topo.rs
- sharding/src/distribution/mod.rs
- sharding/src/distribution/range.rs
- sharding/src/select/by_distance.rs
> Phantom access local

- agent/src/service.rs
- protocol/src/phantom/command.rs
- protocol/src/phantom/mod.rs
- protocol/src/phantom/packet.rs
- protocol/src/redis/command.rs
- protocol/src/redis/mod.rs
- protocol/src/redis/packet.rs
- stream/src/metric.rs
- tests/src/layout.rs
- tests_integration/src/redis/basic/key.rs
- tests_integration/src/redis/basic/limit.rs
- tests_integration/src/redis/mod.rs
对redis协议增加validate校验，避免hang住风险。
> 对redis协议增加validate校验

- discovery/src/socks.rs
为了方便当前业务灰度或测试时，任意更新socks，让mesh只成功更新一次vintage的socklist，后续不再同步该数据了。
> vintage的socklist只会刷新成功一次，之后暂停刷新

- protocol/src/redis/mod.rs
- stream/src/handler.rs
发现redis异常响应后，不panic，改为日志&指标报告。
> log and metric when found redis unexpected response

- ds/src/mem/ring_slice.rs
- stream/src/handler.rs
在解析协议异常时，分别打印：有效的rsp，buff有效位置的后半段，buff有效位置的前半段
> 打印异常response的buff

- agent/src/main.rs
- discovery/src/update.rs
冷启动时，增大固定url的加载频率，避免请求异常时，导致必须信息的延迟加载。
> 启动初期，提高fixed 配置的加载频率

- sharding/src/select/by_distance.rs
> 开启local时，即开启后端资源按quota访问

- endpoint/src/mysql/kvtime.rs
- endpoint/src/mysql/strategy.rs
- endpoint/src/mysql/uuid.rs
- tests/src/mysql_strategy.rs
- tests_integration/src/mysql.rs
> 根据code review，修改uuid相关

- endpoint/src/cacheservice/config.rs
- endpoint/src/cacheservice/topo.rs
- endpoint/src/kv/topo.rs
- endpoint/src/redisservice/config.rs
- endpoint/src/redisservice/topo.rs
- endpoint/src/topo.rs
- sharding/src/select/by_distance.rs
- sharding/src/select/mod.rs
> 为解决dev_selector 分支pull ci编译失败问题，将dev_selector rebase至最新的dev，并新创建分支

- agent/src/main.rs
- ds/src/mem/ring_slice.rs
> data_dump时，从buff起始打印所有内容

- sharding/src/hash/bkdrsub.rs
- sharding/src/hash/mod.rs
- tests/src/all.rs
- tests/src/bkdrsub.rs
- tests/src/hash_test.rs
> 基于82版本的 bkdrsub

- ds/src/mem/ring_slice.rs
- protocol/src/kv/common/io.rs
- protocol/src/kv/common/misc/raw/bytes.rs
- protocol/src/kv/common/misc/raw/int.rs
- protocol/src/kv/common/packets/mod.rs
- protocol/src/kv/common/query_result.rs
- protocol/src/kv/common/value/convert/bigint.rs
- protocol/src/kv/common/value/mod.rs
- protocol/src/kv/packet.rs
- protocol/src/kv/rsppacket.rs
- protocol/src/memcache/binary/packet.rs
- tests/Cargo.toml
- tests/src/benches/ring_slice.rs
- tests/src/ring_slice.rs
- tests/src/size.rs
1 封装ringslice中的ring逻辑；   
2 保持ringSlice的非可变的模型状态。
> 封装ringslice中的ring逻辑+保持不可变特性

- endpoint/src/kv/mod.rs
- endpoint/src/kv/topo.rs
> send 重试时不需要重新计算shard

- endpoint/src/redisservice/config.rs
- protocol/src/memcache/binary/mod.rs
- protocol/src/memcache/binary/packet.rs
1. gets 在miss时，需要返回正确的opcode；
2. getsq 需要返回key。 
3. redis增加dist_check配置，支持不坚持后端数量。
> Dev fixbug 20030829

- protocol/src/kv/mod.rs
- tests_integration/src/mysql.rs
kv访问，需要根据mysql响应进行opcode区分： 
1. value本来不存在，返回opcode应该是NOT Found，NotFound = 0x0001；  
2. 后端返回error，返回opcode为 InvalidArg ,  InvalidArg = 0x0004；
3. del异常，返回opcode为NotStored，NotStored = 0x0005
> sdk需要通过opcode来区分mysql异常

- protocol/src/kv/error.rs
- protocol/src/kv/rsppacket.rs
- sharding/src/hash/crc32.rs
- sharding/src/hash/mod.rs
- tests/src/hash_test.rs
1. auth 异常时，也可能会出先UnhandleResponseError，此时直接上抛异常，断连接。
2. 支持新hash： crc32abs
> Dev update kv error & 支持crc32abs

- ds/src/mem/buffer.rs
- ds/src/mem/bytes.rs
- ds/src/mem/guarded.rs
- ds/src/mem/ring_slice.rs
- protocol/src/redis/command.rs
- protocol/src/redis/packet.rs
- tests/src/benches/ring_slice.rs
- tests/src/ring_slice.rs
1. 把不同的visit_xxx合并成visit_r；
2. fold_xxx => fold_r
3. find_xxx => find
> 优化ring_slice

- endpoint/src/vector/strategy.rs
- protocol/src/vector/command.rs
- protocol/src/vector/mysql.rs
- protocol/src/vector/redis.rs
- tests_integration/src/vector/mod.rs
> 【不merge到dev】add vget command
